[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "cell_simulator"
version = "0.0.1"
description = "Cell simulator: From ODE/SDEs to force vector fields"
authors = [
  { name = "clara_christiansen", email = "clara.christiansen@gmail.com" },
]
license = { file = "LICENSE" }
keywords = ["simulation", "ODE", "SDE"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python :: 3",
]
readme = "README.md"
requires-python = ">=3.11"
dynamic = ["dependencies", "optional-dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools.dynamic.optional-dependencies]
dev = {file = ['requirements_dev.txt']}

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["I", "N", "E", "W"]

[tool.ruff.lint.pep8-naming]
extend-ignore-names = ["F", "F_*", "*_F", "*_pN"]

[tool.coverage.run]
omit = ["tests/*"]

[tool.ruff.lint.per-file-ignores]
"*.ipynb" = ["N803", "N806"]
