from __future__ import annotations

from dataclasses import dataclass
from itertools import product

import numpy as np
import torch

from neural_ode.system import Params, System


@dataclass
class TrajectoryData:
    """A set of ground-truth trajectories on a shared time grid, generated by a :class:`~neural_ode.system.System`.

    Only ``observations`` are shown to the model; ``states`` and ``params``
    are the hidden ground truth, kept for evaluation.
    """

    times: np.ndarray  # (T,)
    observations: np.ndarray  # (N, T, obs_dim)
    states: np.ndarray  # (N, T, state_dim)
    params: Params  # name -> (N,)

    def __len__(self) -> int:
        return self.observations.shape[0]

    def subset(self, idx: np.ndarray) -> TrajectoryData:
        """The trajectories selected by ``idx`` (any numpy index)."""
        return TrajectoryData(
            self.times, self.observations[idx], self.states[idx], {k: v[idx] for k, v in self.params.items()}
        )

    def tensors(self) -> tuple[torch.Tensor, torch.Tensor]:
        """``(times, observations)`` as float32 tensors of shape (T,) and (N, T, obs_dim)."""
        return torch.as_tensor(self.times, dtype=torch.float32), torch.as_tensor(self.observations, dtype=torch.float32)


def simulate_trajectories(
    system: System, params: Params, times: np.ndarray, rng: np.random.Generator, steps_per_frame: int = 10
) -> TrajectoryData:
    """Simulate and observe one trajectory per parameter set.

    Args:
        system: The dynamical system.
        params: Per-trajectory parameters, each of shape (N,).
        times: Frame times, uniformly spaced and starting at 0, shape (T,).
        rng: Randomness for initial states, process noise and observation noise.
        steps_per_frame: Solver sub-steps per frame interval.
    """
    times = np.asarray(times, dtype=float)
    if times[0] != 0.0 or not np.allclose(np.diff(times), times[1] - times[0]):
        raise ValueError("times must start at 0.0 and be uniformly spaced")
    params = {k: np.asarray(v, dtype=float) for k, v in params.items()}
    states = system.simulate(params, times, rng, steps_per_frame)
    return TrajectoryData(times, system.observe(states, params, rng), states, params)


def make_splits(
    system: System, times: np.ndarray, n_train: int, n_val: int, n_test: int, seed: int = 0
) -> dict[str, TrajectoryData]:
    """Train/val/test sets with i.i.d. parameters from ``system.sample_params``.

    Returns:
        ``{"train": ..., "val": ..., "test": ...}``.
    """
    rng = np.random.default_rng(seed)
    data = simulate_trajectories(system, system.sample_params(n_train + n_val + n_test, rng), times, rng)
    idx = np.arange(len(data))
    return {
        "train": data.subset(idx[:n_train]),
        "val": data.subset(idx[n_train : n_train + n_val]),
        "test": data.subset(idx[n_train + n_val :]),
    }


def parameter_grid(system: System, times: np.ndarray, grid: dict[str, np.ndarray], seed: int = 0) -> TrajectoryData:
    """Probe set with every combination of the given parameter values.

    ``grid`` must give values for every parameter of ``system``. Trajectories
    are ordered with the first parameter varying slowest: for
    ``{"omega": [w0, w1], "phase": [p0, p1, p2]}`` the order is
    (w0, p0), (w0, p1), (w0, p2), (w1, p0), ...
    """
    names = list(grid)
    combos = np.array(list(product(*(np.asarray(grid[k], dtype=float) for k in names))))
    params = {k: combos[:, i] for i, k in enumerate(names)}
    return simulate_trajectories(system, params, times, np.random.default_rng(seed))
